// Fetches the Adwaita symbolic icons CmdDeck uses and writes src/icons/adwaita.js.
// Usage: node scripts/adwaita-icons.mjs
// Icons: GNOME Project, LGPL-3.0 or CC BY-SA 3.0 US (see src/icons/LICENSE.md).
import { writeFileSync } from 'node:fs';

const VERSION = '50.0';
const BASE = `https://cdn.jsdelivr.net/gh/GNOME/adwaita-icon-theme@${VERSION}`;

// Keep in sync with src/components/Icons.jsx.
const NAMES = [
  'accessories-text-editor', 'changes-prevent', 'computer', 'dialog-error', 'dialog-question', 'dialog-warning',
  'document-edit', 'document-open-recent', 'document-revert', 'drive-harddisk', 'drive-multidisk', 'edit-copy',
  'edit-undo', 'emblem-important', 'emblem-system', 'folder', 'go-next', 'go-previous', 'help-about',
  'input-keyboard', 'insert-link', 'media-zip', 'network-transmit-receive', 'network-wireless', 'non-starred',
  'object-select', 'package-x-generic', 'pan-down', 'power-profile-performance', 'preferences-color',
  'preferences-system-privacy', 'security-high', 'starred', 'system-run', 'system-search', 'system-users',
  'user-trash', 'utilities-terminal', 'view-grid', 'view-list-bullet', 'view-list-ordered', 'window-close',
];

// Keeps only drawable markup and lets every shape inherit currentColor.
function clean(svg) {
  if (/<image|mask=|filter=/.test(svg)) throw new Error('unsupported markup');
  return svg
    .replace(/^[\s\S]*?<svg[^>]*>/, '')
    .replace(/<\/svg>\s*$/, '')
    .replace(/<!--[\s\S]*?-->/g, '')
    .replace(/<(metadata|title)[\s\S]*?<\/\1>/g, '')
    .replace(/<\w+:[\w-]+\b[^>]*\/>/g, '')
    .replace(/<(\w+):([\w-]+)\b[^>]*>[\s\S]*?<\/\1:\2>/g, '')
    .replace(/xlink:href/g, 'href')
    .replace(/\s[\w-]+:[\w-]+="[^"]*"/g, '')
    .replace(/\s(style|class|color|font-weight|font-family|overflow|white-space|enable-background|display|visibility)="[^"]*"/g, '')
    .replace(/\sfill="(?!none)[^"]*"/g, '')
    // Three decimals is far below a pixel at any size the app uses.
    .replace(/-?\d+\.\d{4,}/g, (n) => String(Math.round(parseFloat(n) * 1000) / 1000))
    .replace(/\s+/g, ' ')
    .trim();
}

const listing = await (await fetch(`https://data.jsdelivr.com/v1/package/gh/GNOME/adwaita-icon-theme@${VERSION}/flat`)).json();
const paths = Object.fromEntries(
  listing.files
    .map((file) => file.name)
    .filter((name) => name.endsWith('-symbolic.svg') && !name.includes('rtl'))
    .map((name) => [name.split('/').pop().replace('-symbolic.svg', ''), name])
);

const lines = [
  '// Adwaita symbolic icons by the GNOME Project (https://www.gnome.org),',
  '// licensed LGPL-3.0 or CC BY-SA 3.0 US; see src/icons/LICENSE.md.',
  `// Generated by scripts/adwaita-icons.mjs from adwaita-icon-theme ${VERSION}. Don't edit by hand.`,
  'export const adwaita = {',
];
for (const name of NAMES) {
  if (!paths[name]) throw new Error(`Missing icon: ${name}`);
  const svg = await (await fetch(`${BASE}${paths[name]}`)).text();
  lines.push(`  '${name}': ${JSON.stringify(clean(svg))},`);
}
lines.push('};', '');
writeFileSync(new URL('../src/icons/adwaita.js', import.meta.url), lines.join('\n'));
console.log(`Wrote ${NAMES.length} icons.`);
